language: c

# Run on the container-based new infrastructure
sudo: false

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=lua5.3

branches:
  only:
    - master

addons:
  apt:
    packages:

before_install:
  - source .travis/setenv_lua.sh
  - luarocks install lpeg
  - luarocks install busted

script:
  - busted -o TAP

notifications:
  email: false
