language: c

# Run on the container-based new infrastructure
sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      lua
      luarocks

before_install:
  - luarocks install lpeg
  - luarocks install busted

script:
  - busted -o TAP

notifications:
  email: false
