language: c

# Run on the container-based new infrastructure
sudo: false

env:
  - LUA: LuaJIT

branches:
  only:
    - master

addons:
  apt:
    packages:

before_install:
  - source .travis_setup.sh
  - luarocks install lpeg
  - luarocks install busted

script:
  - busted -o TAP

notifications:
  email: false
